name: Start build
on: release

jobs:
    build1:
        runs-on: ubuntu-20.04
        services:
            arch:
                image: justkdng/arch-chromium-build-regular
                volumes:
                    - /home/runner/work/ungoogled-chromium-archlinux/ungoogled-chromium-archlinux:/home/build/repo
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
            - name: Signal container to start building
              run: touch start_build
            - name: Wait for build to finish
              shell: bash
              run: .github/workflows/tail_logs.sh
            - name: Restore permissions
              run: sudo chown -R runner $GITHUB_WORKSPACE
            - name: Compress srcdir
              run: tar caf srcdir.tar.zst src/ --remove-files -H posix --atime-preserve
            - name: Upload srcdir
              uses: actions/upload-artifact@v2
              with:
                  name: srcdir.tar.zst
                  path: srcdir.tar.zst
            - name: Upload log file
              uses: actions/upload-artifact@v2
              with:
                  name: logfile
                  path: logfile
    build2:
        runs-on: ubuntu-20.04
        needs: build1
        services:
            arch:
                env:
                    RESUME: 1
                image: justkdng/arch-chromium-build-regular
                volumes:
                    - /home/runner/work/ungoogled-chromium-archlinux/ungoogled-chromium-archlinux:/home/build/repo
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
            - name: Download all artifacts
              uses: actions/download-artifact@v2
            - name: Extract srcdir
              run: tar xf srcdir.tar.zst && rm srcdir.tar.zst
            - name: Signal container to start building
              run: touch start_build
            - name: Wait for build to finish
              shell: bash
              run: .github/workflows/tail_logs.sh
            - name: Restore permissions
              run: sudo chown -R runner $GITHUB_WORKSPACE
            - name: Move resulting packages
              run: |
                  mkdir artifacts
                  mv *.pkg.tar.zst logfile artifacts/
            - name: Upload resulting package
              uses: actions/upload-artifact@v2
              with:
                  name: Resulting package
                  path: artifacts/
            - name: Delete artifact
              uses: geekyeggo/delete-artifact@v1
              with:
                  name: |
                      srcdir.tar.zst
                      logfile
