name: Build and Test
on:
    push:
        branches:
            - master
    
jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
            - name: makepkg
              container:
                  image: justkdng/archlinux:latest
                  options: --tmpfs /build
              run: .github/workflows/check_makepkg.sh

