name: Build ungoogled chromium
on: [push, pull_request]

jobs:
    prepare:
        runs-on: ubuntu-20.04
        container:
            image: justkdng/arch-build-chromium
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
            - name: Prepare environment
              run: .github/workflows/build/env.sh
            - name: Prepare sources
              run: sudo -u build -H bash -c .github/workflows/build/prepare.sh
            - name: Upload sources
              uses: actions/upload-artifact@v2
              with:
                  name: res
                  path: /home/build/res/
    obs_build:
        env:
            OBS_AUTH: ${{ secrets.OBS_AUTH }}
        needs: prepare
        runs-on: ubuntu-latest
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
            - name: Trigger OBS build
              if: ${{ env.OBS_AUTH != 0 }}
              shell: bash
              run: .github/workflows/obs_upload.sh
    build_1:
        runs-on: ubuntu-20.04
        needs: prepare
        container:
            image: justkdng/arch-build-chromium
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
            - name: Download artifacts
              uses: actions/download-artifact@v2
              with:
                  name: res
            - name: Prepare environment
              run: .github/workflows/build/env.sh
            - name: Extract sources
              run: .github/workflows/build/extract.sh
            - name: Build package
              run: sudo -u build -H bash -c .github/workflows/build/build.sh
            - name: Upload artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: res
                  path: /home/build/res/
    build_2:
        runs-on: ubuntu-20.04
        needs: build_1
        container:
            image: justkdng/arch-build-chromium
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
            - name: Download artifacts
              uses: actions/download-artifact@v2
              with:
                  name: res
            - name: Prepare environment
              run: .github/workflows/build/env.sh
            - name: Extract sources
              run: .github/workflows/build/extract.sh
            - name: Build package
              run: sudo -u build -H bash -c .github/workflows/build/build.sh
            - name: Upload artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: res
                  path: /home/build/res/
    build_3:
        runs-on: ubuntu-20.04
        needs: build_2
        container:
            image: justkdng/arch-build-chromium
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
            - name: Download artifacts
              uses: actions/download-artifact@v2
              with:
                  name: res
            - name: Prepare environment
              run: .github/workflows/build/env.sh
            - name: Extract sources
              run: .github/workflows/build/extract.sh
            - name: Build package
              run: sudo -u build -H bash -c .github/workflows/build/build.sh
            - name: Upload artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: res
                  path: /home/build/res/
    build_4:
        runs-on: ubuntu-20.04
        needs: build_3
        container:
            image: justkdng/arch-build-chromium
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
            - name: Download artifacts
              uses: actions/download-artifact@v2
              with:
                  name: res
            - name: Prepare environment
              run: .github/workflows/build/env.sh
            - name: Extract sources
              run: .github/workflows/build/extract.sh
            - name: Build package
              run: sudo -u build -H bash -c .github/workflows/build/build.sh
            - name: Upload artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: res
                  path: /home/build/res/
