name: Start build
on: [push, pull_request]

jobs:
    prepare_sources:
        runs-on: ubuntu-20.04
        container:
            image: justkdng/arch-build-chromium
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
            - name: Update system
              run: pacman -Syu --noconfirm
            - name: Build package
              shell: bash
              run: |
                  shopt -s dotglob
                  cp -r * /home/build
                  chown -R build /home/build
                  su build
                  cd /home/build
                  makepkg --nobuild --nodeps
                  tar caf srcdir.tar.zst src/ --remove-file -H posix --atime-preserve
            - name: Upload source dir
              uses: actions/upload-artifact@v2
              with:
                  name: srcdir.tar.zst
                  path: /home/build/srcdir.tar.zst
