name: Build ungoogled chromium
on: [push, pull_request]

jobs:
    prepare:
        runs-on: ubuntu-20.04
        container:
            image: justkdng/arch-build-chromium
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
            - name: Update system
              run: pacman -Syu --noconfirm
            - name: Setup environment
              run: .github/workflows/build/env.sh
            - name: Prepare sources
              run: sudo -u build -H bash -c .github/workflows/build/prepare.sh
            - name: Upload sources
              uses: actions/upload-artifact@v2
              with:
                  name: src
                  path: /home/build/src.tar.zst
    build_1:
        runs-on: ubuntu-20.04
        needs: prepare
        container:
            image: justkdng/arch-build-chromium
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
            - name: Download artifacts
              uses: actions/download-artifact@v2
            - name: Delete src artifact
              uses: geekyeggo/delete-artifact@v1
              with:
                  name: src
            - name: Update system
              run: pacman -Syu --noconfirm
            - name: Setup environment
              run: .github/workflows/build/env.sh
            - name: Extract sources
              run: .github/workflows/build/extract.sh
            - name: Build package
              run: sudo -u build -H bash -c .github/workflows/build/build.sh
            - name: Upload sources
              uses: actions/upload-artifact@v2
              with:
                  name: src
                  path: /home/build/src.tar.zst
    build_2:
        runs-on: ubuntu-20.04
        needs: build_1
        container:
            image: justkdng/arch-build-chromium
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
            - name: Download artifacts
              uses: actions/download-artifact@v2
            - name: Delete src artifact
              uses: geekyeggo/delete-artifact@v1
              with:
                  name: src
            - name: Update system
              run: pacman -Syu --noconfirm
            - name: Setup environment
              run: .github/workflows/build/env.sh
            - name: Extract sources
              run: .github/workflows/build/extract.sh
            - name: Build package
              run: sudo -u build -H bash -c .github/workflows/build/build.sh
            - name: Upload sources
              uses: actions/upload-artifact@v2
              with:
                  name: src
                  path: /home/build/src.tar.zst
    package:
        runs-on: ubuntu-20.04
        needs: build_2
        container:
            image: justkdng/arch-build-chromium
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
            - name: Download artifacts
              uses: actions/download-artifact@v2
            - name: Update system
              run: pacman -Syu --noconfirm
            - name: Setup environment
              run: .github/workflows/build/env.sh
            - name: Extract sources
              run: .github/workflows/build/extract.sh
            - name: Build package
              run: sudo -u build -H bash -c .github/workflows/build/package.sh
            - name: Upload package
              uses: actions/upload-artifact@v2
              with:
                  name: artifact
                  path: /home/build/artifacts
            - name: Delete src artifact
              uses: geekyeggo/delete-artifact@v1
              with:
                  name: src

        
