name: Build ungoogled chromium
on: [push, pull_request]

jobs:
    prepare:
        runs-on: ubuntu-20.04
        container:
            image: justkdng/arch-build-chromium
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
            - name: Prepare environment
              run: .github/workflows/build/env.sh
            - name: Prepare sources
              run: sudo -u build -H bash -c .github/workflows/build/prepare.sh
            - name: Upload sources
              uses: actions/upload-artifact@v2
              with:
                  name: src
                  path: /home/build/src.txt
    build_1:
        runs-on: ubuntu-20.04
        needs: prepare
        container:
            image: justkdng/arch-build-chromium
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
            - name: Download artifacts
              uses: actions/download-artifact@v2
            - name: Prepare environment
              run: .github/workflows/build/env.sh
            - name: Extract sources
              run: .github/workflows/build/extract.sh
            - name: Build package
              run: sudo -u build -H bash -c .github/workflows/build/build.sh
            - name: Upload source url
              uses: actions/upload-artifact@v2
              with:
                  name: src
                  path: /home/build/src.txt
            - name: Upload resulting package
              if: failure()
              with:
                  name: pkg
                  path: /home/build/artifacts
    build_2:
        runs-on: ubuntu-20.04
        needs: build_1
        container:
            image: justkdng/arch-build-chromium
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
            - name: Download artifacts
              uses: actions/download-artifact@v2
            - name: Prepare environment
              run: .github/workflows/build/env.sh
            - name: Extract sources
              run: .github/workflows/build/extract.sh
            - name: Build package
              run: sudo -u build -H bash -c .github/workflows/build/build.sh
            - name: Upload source url
              uses: actions/upload-artifact@v2
              with:
                  name: src
                  path: /home/build/src.txt
            - name: Upload resulting package
              if: failure()
              with:
                  name: pkg
                  path: /home/build/artifacts
    build_3:
        runs-on: ubuntu-20.04
        needs: build_2
        container:
            image: justkdng/arch-build-chromium
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
            - name: Download artifacts
              uses: actions/download-artifact@v2
            - name: Prepare environment
              run: .github/workflows/build/env.sh
            - name: Extract sources
              run: .github/workflows/build/extract.sh
            - name: Build package
              run: sudo -u build -H bash -c .github/workflows/build/build.sh
            - name: Upload source url
              uses: actions/upload-artifact@v2
              with:
                  name: src
                  path: /home/build/src.txt
            - name: Upload resulting package
              if: failure()
              with:
                  name: pkg
                  path: /home/build/artifacts
    build_4:
        runs-on: ubuntu-20.04
        needs: build_3
        container:
            image: justkdng/arch-build-chromium
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
            - name: Download artifacts
              uses: actions/download-artifact@v2
            - name: Prepare environment
              run: .github/workflows/build/env.sh
            - name: Extract sources
              run: .github/workflows/build/extract.sh
            - name: Build package
              run: sudo -u build -H bash -c .github/workflows/build/build.sh
            - name: Upload source url
              uses: actions/upload-artifact@v2
              with:
                  name: src
                  path: /home/build/src.txt
            - name: Upload resulting package
              if: failure()
              with:
                  name: pkg
                  path: /home/build/artifacts
