name: Start build
on: [push, pull_request]

jobs:
    build1:
        runs-on: ubuntu-20.04
        container:
            image: justkdng/arch-build-chromium
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
            - name: View files
              run: |
                  ls -a $HOME
