name: Build and Test
on:
    push:
        branches:
            - master

jobs:
    main:
        runs-on: ubuntu-latest
        container:
            image: justkdng/archlinux:latest
            options: --tmpfs /build
        steps:
            - name: checkout
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
            - name: makepkg
              run: .github/workflows/check_makepkg.sh

