name: Check PKGBUILD
on:
    push:
        branches:
            - master
    
jobs:
    build:
        name: "Check PKGBUILD"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: makepkg
              uses: jstkdng/arch-check-pkgbuild@master
