name: Testing...
on: [push, pull_request]

jobs:
    client:
        env:
            WORKERS: "10.200.200.102/10.200.200.103/10.200.200.104/10.200.200.105"
        runs-on: ubuntu-20.04
        services:
            arch:
                image: justkdng/arch-build-client
                ports:
                    - 3632:3632
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
            - name: Setup wireguard
              shell: bash
              env:
                  WGCONF: ${{ secrets.WG1 }}
              run: .github/workflows/wireguard_setup.sh
            - name: Show makepkg log
              run: |
                  pwd
                  ls -a
                  tail -F ungoogled-chromium-83.0.4103.97-2-x86_64-build.log
            - name: Terminate workers
              run: go run .github/workflows/end_workers.go
    volunteer2:
        runs-on: ubuntu-20.04
        services:
            arch:
                env:
                    DISTCC_ARGS: "--allow-private --allow 10.200.200.101"
                image: justkdng/arch-build-worker
                ports:
                    - 3632:3632
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
            - name: Setup wireguard
              shell: bash
              env:
                  WGCONF: ${{ secrets.WG2 }}
              run: .github/workflows/wireguard_setup.sh
            - name: Wait for shutdown signal
              run: go run .github/workflows/server.go
    volunteer3:
        runs-on: ubuntu-20.04
        services:
            arch:
                env:
                    DISTCC_ARGS: "--allow-private --allow 10.200.200.101"
                image: justkdng/arch-build-worker
                ports:
                    - 3632:3632
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
            - name: Setup wireguard
              shell: bash
              env:
                  WGCONF: ${{ secrets.WG3 }}
              run: .github/workflows/wireguard_setup.sh
            - name: Wait for shutdown signal
              run: go run .github/workflows/server.go
    volunteer4:
        runs-on: ubuntu-20.04
        services:
            arch:
                env:
                    DISTCC_ARGS: "--allow-private --allow 10.200.200.101"
                image: justkdng/arch-build-worker
                ports:
                    - 3632:3632
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
            - name: Setup wireguard
              shell: bash
              env:
                  WGCONF: ${{ secrets.WG4 }}
              run: .github/workflows/wireguard_setup.sh
            - name: Wait for shutdown signal
              run: go run .github/workflows/server.go
    volunteer5:
        runs-on: ubuntu-20.04
        services:
            arch:
                env:
                    DISTCC_ARGS: "--allow-private --allow 10.200.200.101"
                image: justkdng/arch-build-worker
                ports:
                    - 3632:3632
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
            - name: Setup wireguard
              shell: bash
              env:
                  WGCONF: ${{ secrets.WG5 }}
              run: .github/workflows/wireguard_setup.sh
            - name: Wait for shutdown signal
              run: go run .github/workflows/server.go
