name: Testing...
on: [push, pull_request]

jobs:
    test-worker:
        runs-on: ubuntu-latest
        services:
            arch:
                image: justkdng/arch-build-worker
                ports:
                    - 8189:8189
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
            - name: Setup wireguard
              shell: bash
              env:
                  WGCONF: ${{ secrets.WG1 }}
              run: .github/workflows/wireguard_setup.sh
            - name: Wait for shutdown signal
              run: go run .github/workflows/server.go
