name: Start build
on: [push, pull_request]

jobs:
    client:
        runs-on: ubuntu-20.04
        services:
            arch:
                image: justkdng/arch-chromium-build-client
                env:
                    WORKERS: "10.200.200.102/10.200.200.103/10.200.200.104/10.200.200.105"
                volumes:
                    - /home/runner/work/ungoogled-chromium-archlinux/ungoogled-chromium-archlinux:/home/build/repo
                ports:
                    - 3632:3632
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
            - name: Setup wireguard
              shell: bash
              env:
                  WGCONF: ${{ secrets.WG1 }}
              run: .github/workflows/wireguard_setup.sh
            - name: Tail logs
              run: tail -F logfile
    volunteer2:
        runs-on: ubuntu-20.04
        services:
            arch:
                env:
                    DISTCC_ARGS: "--allow 10.200.200.101 --log-file /tmp/distccd.log"
                image: justkdng/arch-chromium-build-volunteer
                ports:
                    - 3632:3632
                volumes:
                    - /tmp:/tmp
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
            - name: Setup wireguard
              shell: bash
              env:
                  WGCONF: ${{ secrets.WG2 }}
              run: .github/workflows/wireguard_setup.sh
            - name: Wait for shutdown signal
              shell: bash
              run: .github/workflows/volunteer_logs.sh
    volunteer3:
        runs-on: ubuntu-20.04
        services:
            arch:
                env:
                    DISTCC_ARGS: "--allow 10.200.200.101 --log-file /tmp/distccd.log"
                image: justkdng/arch-chromium-build-volunteer
                ports:
                    - 3632:3632
                volumes:
                    - /tmp:/tmp
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
            - name: Setup wireguard
              shell: bash
              env:
                  WGCONF: ${{ secrets.WG3 }}
              run: .github/workflows/wireguard_setup.sh
            - name: Wait for shutdown signal
              shell: bash
              run: .github/workflows/volunteer_logs.sh
    volunteer4:
        runs-on: ubuntu-20.04
        services:
            arch:
                env:
                    DISTCC_ARGS: "--allow 10.200.200.101 --log-file /tmp/distccd.log"
                image: justkdng/arch-chromium-build-volunteer
                ports:
                    - 3632:3632
                volumes:
                    - /tmp:/tmp
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
            - name: Setup wireguard
              shell: bash
              env:
                  WGCONF: ${{ secrets.WG4 }}
              run: .github/workflows/wireguard_setup.sh
            - name: Wait for shutdown signal
              shell: bash
              run: .github/workflows/volunteer_logs.sh
    volunteer5:
        runs-on: ubuntu-20.04
        services:
            arch:
                env:
                    DISTCC_ARGS: "--allow 10.200.200.101 --log-file /tmp/distccd.log"
                image: justkdng/arch-chromium-build-volunteer
                ports:
                    - 3632:3632
                volumes:
                    - /tmp:/tmp
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
            - name: Setup wireguard
              shell: bash
              env:
                  WGCONF: ${{ secrets.WG5 }}
              run: .github/workflows/wireguard_setup.sh
            - name: Wait for shutdown signal
              shell: bash
              run: .github/workflows/volunteer_logs.sh
