name: Trigger OBS build
on: push
jobs:
    build:
        name: "Trigger OBS"
        runs-on: ubuntu-latest
        steps:
            - name: curl
              uses: enflo/curl-action@master
              with:
                curl: "-XPOST -H 'Content-Type: application/octet-stream' -H 'Authorization: ${{ secrets.obs_master }}' 'https://build.opensuse.org/trigger/runservice'"
