name: Trigger OBS build

on: push

jobs:
    trigger_obs:
        - name: HTTP Request Action
          uses: fjogeleit/http-request-action@v1.2.0
          with:
              url: "https://build.opensuse.org/trigger/runservice"
              method: "POST"
              customHeaders: "{
                'Authentication':'${{ secrets.obs_master }}',
                'project':'home:justkidding:arch'
                'package':'ungoogled-chromium'
              }"
