name: Start build
on: [push, pull_request]

jobs:
    main:
        runs-on: ubuntu-20.04
        services:
            arch:
                image: justkdng/arch-chromium-build-regular
                volumes:
                    - /home/runner/work/ungoogled-chromium-archlinux/ungoogled-chromium-archlinux:/home/build/repo
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v2
            - name: Tail logs
              run: tail -F logfile
